# -*- encoding : utf-8 -*-
# This file was generated by the "jdbc" generator, which is provided
# by the activerecord-jdbc-adapter gem.
#
# This file allows the JDBC drivers to be hooked into ActiveRecord
# such that you don't have to change anything else in your Rails
# application.
if RUBY_PLATFORM == 'java'
  require 'arjdbc' 
  require File.join(Gem.loaded_specs['jdbc-sqlite3'].full_gem_path, 'lib/sqlite-jdbc-3.7.2.jar')
end
